version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/Promise
    branches:
      only:
        - master
    steps:
        - checkout
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run: npm install
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
        - run: npm test
        - run: npm run coverage
        - run: npm i -g codecov
        - run: codecov
